Add Django view example to README
dmathieu/sabayon pull request #36
Opened 2016-12-26 01:44 UTC by tobiasmcnulty

2016-12-26 09:17 UTC, jezdez approved these changes
Just minor nits, :+1:

2016-12-26 09:17 UTC, jezdez commented on README.md
> +    def find_key(token):
Could this function be moved outside of the view function to reduce code smell?

2016-12-26 09:17 UTC, jezdez commented on README.md
> +```
Missing import of the acme view function

2016-12-26 09:17 UTC, jezdez commented on README.md
> +def acme(request, token):
Maybe call this `acme_challenge` instead?

2017-01-03 13:39 UTC, dmathieu requested changes
Thank you for this PR.
Could you apply the changes suggested by @jezdez?

2017-01-04 08:36 UTC, dmathieu commented on README.md
> +    def find_key(token):
Any reason why you didn't move this function out of the `acme_challenge` one?
I'm not practicing Python a lot. But it looks quite weird.

Also, if you do move it out, could you rename it to `find_acme_key`?

2017-01-18 03:45 UTC, ntravis commented
looks exactly like my working implementation. Wish I had seen the PR first, but I came back to add one after I worked out the same code 👍

2017-01-18 07:14 UTC, dmathieu approved these changes

2017-01-18 07:14 UTC, merged